# Linter Options
options:
  merge-default-rules: false
  formatter: stylish
# File Options
files:
  include: 'assets/sass/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation: 0
  indentation: 0
  property-sort-order: 1
  variable-for-property: 0
  border-zero: 1
  final-newline: 0
  leading-zero: 0
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-important: 1
  no-qualifying-elements: 0
  quotes: 0
