import type { FloorDimensions, Region } from "./floor";

const PLAN_LOGICAL_DIMENSIONS: FloorDimensions = {
  // Width includes the 4-cell left margin before dock 99.
  width: 54,
  height: 21,
};

const FLOOR_PLAN_HORIZONTAL_SCALE = 1;
export const FLOOR_PLAN_LEFT_MARGIN = 4;

export const FLOOR_PLAN_DIMENSIONS: FloorDimensions = {
  width: PLAN_LOGICAL_DIMENSIONS.width * FLOOR_PLAN_HORIZONTAL_SCALE,
  height: PLAN_LOGICAL_DIMENSIONS.height,
};

function scaleRegionHorizontally(region: Region, scale: number): Region {
  const logicalWidth = region.endX - region.startX + 1;
  const startX = region.startX * scale;
  return {
    ...region,
    startX,
    endX: startX + logicalWidth * scale - 1,
  };
}

const FLOOR_PLAN_DOOR_IDS = [
  "99",
  "98",
  "97",
  "96",
  "95",
  "94",
  "93",
  "92",
  "91",
  "90",
  "89",
  "88",
  "87",
  "86",
  "85",
  "84",
  "83",
];

const FLOOR_PLAN_DOORS: Region[] = FLOOR_PLAN_DOOR_IDS.map((door, idx) => {
  const startX = FLOOR_PLAN_LEFT_MARGIN + idx * 3;
  return {
    id: `door_${door}`,
    label: door,
    type: "door",
    startX,
    startY: 1,
    endX: startX + 1,
    endY: 1,
    color: "oklch(from #6b7280 l c h)",
  };
});

const FLOOR_PLAN_SLOTS: Region[] = [
  {
    id: "slot_2x3_1",
    label: "2x3 #1",
    type: "lane",
    startX: 4,
    startY: 2,
    endX: 5,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_3",
    label: "2x3 #3",
    type: "lane",
    startX: 7,
    startY: 2,
    endX: 8,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_4",
    label: "2x3 #4",
    type: "lane",
    startX: 10,
    startY: 2,
    endX: 11,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_5",
    label: "2x3 #5",
    type: "lane",
    startX: 13,
    startY: 2,
    endX: 14,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_6",
    label: "2x3 #6",
    type: "lane",
    startX: 16,
    startY: 2,
    endX: 17,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_7",
    label: "2x3 #7",
    type: "lane",
    startX: 19,
    startY: 2,
    endX: 20,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_8",
    label: "2x3 #8",
    type: "lane",
    startX: 22,
    startY: 2,
    endX: 23,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_9",
    label: "2x3 #9",
    type: "lane",
    startX: 34,
    startY: 2,
    endX: 35,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_10",
    label: "2x3 #10",
    type: "lane",
    startX: 37,
    startY: 2,
    endX: 38,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_11",
    label: "2x3 #11",
    type: "lane",
    startX: 40,
    startY: 2,
    endX: 41,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_12",
    label: "2x3 #12",
    type: "lane",
    startX: 43,
    startY: 2,
    endX: 44,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_13",
    label: "2x3 #13",
    type: "lane",
    startX: 46,
    startY: 2,
    endX: 47,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_14",
    label: "2x3 #14",
    type: "lane",
    startX: 49,
    startY: 2,
    endX: 50,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_15",
    label: "2x3 #15",
    type: "lane",
    startX: 52,
    startY: 2,
    endX: 53,
    endY: 4,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_16",
    label: "2x3 #16",
    type: "lane",
    startX: 4,
    startY: 5,
    endX: 5,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_17",
    label: "2x3 #17",
    type: "lane",
    startX: 7,
    startY: 5,
    endX: 8,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_18",
    label: "2x3 #18",
    type: "lane",
    startX: 10,
    startY: 5,
    endX: 11,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_19",
    label: "2x3 #19",
    type: "lane",
    startX: 13,
    startY: 5,
    endX: 14,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_20",
    label: "2x3 #20",
    type: "lane",
    startX: 16,
    startY: 5,
    endX: 17,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_21",
    label: "2x3 #21",
    type: "lane",
    startX: 19,
    startY: 5,
    endX: 20,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_22",
    label: "2x3 #22",
    type: "lane",
    startX: 22,
    startY: 5,
    endX: 23,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_23",
    label: "2x3 #23",
    type: "lane",
    startX: 34,
    startY: 5,
    endX: 35,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_24",
    label: "2x3 #24",
    type: "lane",
    startX: 37,
    startY: 5,
    endX: 38,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_25",
    label: "2x3 #25",
    type: "lane",
    startX: 40,
    startY: 5,
    endX: 41,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_26",
    label: "2x3 #26",
    type: "lane",
    startX: 43,
    startY: 5,
    endX: 44,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_27",
    label: "2x3 #27",
    type: "lane",
    startX: 46,
    startY: 5,
    endX: 47,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_28",
    label: "2x3 #28",
    type: "lane",
    startX: 49,
    startY: 5,
    endX: 50,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_29",
    label: "2x3 #29",
    type: "lane",
    startX: 52,
    startY: 5,
    endX: 53,
    endY: 7,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_30",
    label: "2x3 #30",
    type: "lane",
    startX: 16,
    startY: 9,
    endX: 17,
    endY: 11,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_31",
    label: "2x3 #31",
    type: "lane",
    startX: 19,
    startY: 9,
    endX: 20,
    endY: 11,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_32",
    label: "2x3 #32",
    type: "lane",
    startX: 34,
    startY: 9,
    endX: 35,
    endY: 11,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_33",
    label: "2x3 #33",
    type: "lane",
    startX: 37,
    startY: 9,
    endX: 38,
    endY: 11,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_34",
    label: "2x3 #34",
    type: "lane",
    startX: 49,
    startY: 9,
    endX: 50,
    endY: 11,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_2x3_35",
    label: "2x3 #35",
    type: "lane",
    startX: 52,
    startY: 9,
    endX: 53,
    endY: 11,
    color: "oklch(from #22d3ee l c h)",
  },
  {
    id: "slot_1x6_1",
    label: "1x6 #1",
    type: "lane",
    startX: 2,
    startY: 9,
    endX: 2,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_2",
    label: "1x6 #2",
    type: "lane",
    startX: 4,
    startY: 9,
    endX: 4,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_3",
    label: "1x6 #3",
    type: "lane",
    startX: 5,
    startY: 9,
    endX: 5,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_4",
    label: "1x6 #4",
    type: "lane",
    startX: 7,
    startY: 9,
    endX: 7,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_5",
    label: "1x6 #5",
    type: "lane",
    startX: 8,
    startY: 9,
    endX: 8,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_6",
    label: "1x6 #6",
    type: "lane",
    startX: 10,
    startY: 9,
    endX: 10,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_7",
    label: "1x6 #7",
    type: "lane",
    startX: 11,
    startY: 9,
    endX: 11,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_8",
    label: "1x6 #8",
    type: "lane",
    startX: 13,
    startY: 9,
    endX: 13,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_9",
    label: "1x6 #9",
    type: "lane",
    startX: 14,
    startY: 9,
    endX: 14,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_10",
    label: "1x6 #10",
    type: "lane",
    startX: 40,
    startY: 9,
    endX: 40,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_11",
    label: "1x6 #11",
    type: "lane",
    startX: 41,
    startY: 9,
    endX: 41,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_12",
    label: "1x6 #12",
    type: "lane",
    startX: 43,
    startY: 9,
    endX: 43,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_13",
    label: "1x6 #13",
    type: "lane",
    startX: 44,
    startY: 9,
    endX: 44,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_14",
    label: "1x6 #14",
    type: "lane",
    startX: 46,
    startY: 9,
    endX: 46,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
  {
    id: "slot_1x6_15",
    label: "1x6 #15",
    type: "lane",
    startX: 47,
    startY: 9,
    endX: 47,
    endY: 14,
    color: "oklch(from #a855f7 l c h)",
  },
];

const FLOOR_PLAN_LOGICAL_REGIONS: Region[] = [...FLOOR_PLAN_DOORS, ...FLOOR_PLAN_SLOTS];

export const floorPlanRegions: Region[] = FLOOR_PLAN_LOGICAL_REGIONS.map((region) =>
  scaleRegionHorizontally(region, FLOOR_PLAN_HORIZONTAL_SCALE),
);
