/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TRouteImport } from './routes/t'
import { Route as QRouteImport } from './routes/q'
import { Route as PRouteImport } from './routes/p'
import { Route as BRouteImport } from './routes/b'
import { Route as IndexRouteImport } from './routes/index'

const TRoute = TRouteImport.update({
  id: '/t',
  path: '/t',
  getParentRoute: () => rootRouteImport,
} as any)
const QRoute = QRouteImport.update({
  id: '/q',
  path: '/q',
  getParentRoute: () => rootRouteImport,
} as any)
const PRoute = PRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const BRoute = BRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/p': typeof PRoute
  '/q': typeof QRoute
  '/t': typeof TRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/p': typeof PRoute
  '/q': typeof QRoute
  '/t': typeof TRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/p': typeof PRoute
  '/q': typeof QRoute
  '/t': typeof TRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b' | '/p' | '/q' | '/t'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b' | '/p' | '/q' | '/t'
  id: '__root__' | '/' | '/b' | '/p' | '/q' | '/t'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BRoute: typeof BRoute
  PRoute: typeof PRoute
  QRoute: typeof QRoute
  TRoute: typeof TRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/t': {
      id: '/t'
      path: '/t'
      fullPath: '/t'
      preLoaderRoute: typeof TRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q': {
      id: '/q'
      path: '/q'
      fullPath: '/q'
      preLoaderRoute: typeof QRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BRoute: BRoute,
  PRoute: PRoute,
  QRoute: QRoute,
  TRoute: TRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
