import { BASE_FLOOR_DIMENSIONS, floorRegions, floorToMatrix } from "@/lib/floor";

describe("floorToMatrix", () => {
  it("renders the HNY3 layout (21 logical cols, doubled width) without overlaps", () => {
    const matrix = floorToMatrix(
      floorRegions,
      BASE_FLOOR_DIMENSIONS.width,
      BASE_FLOOR_DIMENSIONS.height,
    );

    const logicalMatrix = [
      [
        "0",
        "leadership",
        "door_99",
        "door_98",
        "door_97",
        "door_96",
        "door_95",
        "door_94",
        "door_93",
        "door_92",
        "door_91",
        "door_90",
        "door_89",
        "door_88",
        "door_87",
        "door_86",
        "door_85",
        "door_84",
        "door_83",
        "0",
        "0",
      ],
      [
        "0",
        "0",
        "i_1",
        "i_2",
        "i_3",
        "i_4",
        "i_5",
        "i_6",
        "i_7",
        "0",
        "0",
        "down_stack",
        "down_stack",
        "down_stack",
        "i_8",
        "i_9",
        "i_10",
        "i_11",
        "i_12",
        "0",
        "0",
      ],
      [
        "0",
        "0",
        "f_1",
        "f_2",
        "f_3",
        "f_4",
        "f_5",
        "f_6",
        "0",
        "0",
        "j_2",
        "down_stack",
        "down_stack",
        "down_stack",
        "f_7",
        "f_8",
        "f_9",
        "f_10",
        "f_11",
        "f_12",
        "g_2",
      ],
      [
        "0",
        "0",
        "c_1",
        "c_2",
        "c_3",
        "c_4",
        "c_5",
        "c_6",
        "c_7",
        "cp2",
        "xl1",
        "xl3",
        "area",
        "area",
        "area",
        "xl4",
        "xl6",
        "g1",
        "g3",
        "ex1",
        "xl7",
      ],
    ];

    const doubleRow = (row: string[]) => row.flatMap((cell) => [cell, cell]);
    const expected = logicalMatrix.map(doubleRow);

    expect(matrix).toEqual(expected);
  });
});
